name: "Surefire"
on:
  push:
    branches:
      - main
      - 'TRI-**'
      - 'feature/**'
      - 'bugfix/**'
      - 'fix/**'
      - 'chore/**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    name: surefire-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-main-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      _ name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        - run: cd tests && mvn clean test --batch-mode -Dmaven.test.failure.ignore=true

        - name:
        - uses: scacap/action-surefire-report@master
          if: endsWith(github.ref, 'master') == false
          with:
            check_name: IRS Surefire Test Report

